---
abstract: 'Tapper - Context sensitive connected DBIC schema'
author:
  - 'AMD OSRC Tapper Team <tapper@amd64.org>'
build_requires:
  Data::DPath: 0.17
  ExtUtils::MakeMaker: 6.42
  Tapper::Test: 3.000002
  Test::Fixture::DBIC::Schema: 0.02
  Test::More: 0
  Test::Perl::Critic: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: freebsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tapper-Model
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Memoize: 0
  Tapper::Config: 3.000002
  Tapper::Schema: 3.000002
  parent: 0
  perl: 5.010
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Tapper-Model
  repository: git://github.com/amd/Tapper-Reports-Model.git
version: 3.000004
